Esram.Davetiye.Web.App/Models/Entities/Product.cs
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Esram.Davetiye.Web.App.Models.Entities
{
    public class Product
    {
        public int Id { get; set; }
        [DisplayName("Ürün adı : ")]
        [Required(ErrorMessage ="Ürün adı boş geçilemez")]
        public string Name { get; set; }
        [DisplayName("Ürün kodu : ")]
        [Required(ErrorMessage ="Ürün kodu boş geçilemez")]
        public string Code { get; set; }
        [DisplayName("Ürün açıklaması : ")]
        public string Description { get; set; }
        [DisplayName("Kapak resmi : ")]
        public string MainPicture { get; set; }
        [DisplayName("Çok tercih edilen olarak işaretle : ")]
        public bool IsBest { get; set; }
        [DisplayName("Fiyat : ")]
        public string Price { get; set; }
        [DisplayName("Kategori : ")]
        [Required(ErrorMessage ="Lütfen kategori seçiniz")]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        [DisplayName("Diğer resimler :")]
        public virtual ICollection<ProductPicture> Pictures { get; set; }
    }
}

Esram.Davetiye.Web.App/Areas/ritapanel/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Esram.Davetiye.Web.App.Areas.ritapanel.Models.ViewModels;
using Esram.Davetiye.Web.App.Manage.Filters;
using Esram.Davetiye.Web.App.Models.Context;
using Esram.Davetiye.Web.App.Models.Entities;
using Esram.Davetiye.Web.App.Models.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;

namespace Esram.Davetiye.Web.App.Areas.ritapanel.Controllers
{
    [Authentication]
    [Area("ritapanel")]
    public class CategoryController : Controller
    {
        [Route("ritapanel/kategoriler")]
        public async Task<IActionResult> Index()
        {
            using var context = new EsramDbContext();
            var categories = await context.MasterCategories.Include(x => x.Categories).OrderByDescending(x=>x.Id).ToListAsync();
            CategoryViewModel vm = new CategoryViewModel
            {
                MasterCategories = categories,
                MasterCategory = new MasterCategory()
            };
            return View(vm);
        }

        [HttpPost]
        [Route("addmaster")]
        public async Task<IActionResult> AddMasterCategory(MasterCategory masterCategory,IFormFile McPicturePath)
        {
            if (McPicturePath!=null)
                masterCategory.PicturePath = FileExtension.UploadFile(McPicturePath, "wwwroot/static/uploads/categories").Replace(@"\", "/");
            using var context = new EsramDbContext();
            context.MasterCategories.Add(masterCategory);
            int result = await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("deletemaster")]
        public async Task<IActionResult> DeleteMasterCategory(int id)
        {
            using var context = new EsramDbContext();
            var mc = await context.MasterCategories.FirstOrDefaultAsync(x => x.Id == id);
            context.MasterCategories.Remove(mc);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("editmodal")]
        public async Task<IActionResult> EditModal(int mcid)
        {
            using var context = new EsramDbContext();
            var mc = await context.MasterCategories.FirstOrDefaultAsync(x => x.Id == mcid);
            return ViewComponent("EditModal", mc);
        }

        [HttpPost]
        [Route("editcategorymodal")]
        public async Task<IActionResult> EditCategoryModal(int cid)
        {
            using var context = new EsramDbContext();
            var cat = await context.Categories.FirstOrDefaultAsync(x => x.Id == cid);
            return ViewComponent("EditCategoryModal", cat);
        }

        [HttpPost]
        [Route("editcategory")]
        public async Task<IActionResult> EditCategory(Category cat, IFormFile PicturePath)
        {
            if (PicturePath != null)
                cat.PicturePath = FileExtension.UploadFile(PicturePath, "wwwroot/static/uploads/categories").Replace(@"\", "/");
            using var context = new EsramDbContext();
            context.Categories.Update(cat);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("editmaster")]
        public async Task<IActionResult> EditMasterCategory(MasterCategory mc,IFormFile PicturePath)
        {
            if (PicturePath != null)
                mc.PicturePath = FileExtension.UploadFile(PicturePath, "wwwroot/static/uploads/categories").Replace(@"\", "/");
            using var context = new EsramDbContext();
            context.MasterCategories.Update(mc);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Route("deletecategory")]
        public async Task<IActionResult> DeleteCategory(int cid)
        {
           
                using var context = new EsramDbContext();
                var cat = await context.Categories.FirstOrDefaultAsync(x => x.Id == cid);
                context.Categories.Remove(cat);
                int result = await context.SaveChangesAsync();
                return result>0?Json(true):Json(false);
        }

        [HttpPost]
        [Route("addcategorymodal")]
        public IActionResult AddCategoryModal(int mcid)
        {
            var cat = new Category
            {
                MasterCategoryId = mcid
            };
            return ViewComponent("AddCategoryModal", cat);
        }

        [HttpPost]
        [Route("addcategory")]
        public async Task<IActionResult> AddCategory(Category category,IFormFile PicturePath)
        {
            using var context = new EsramDbContext();
            if (PicturePath != null)
                category.PicturePath = FileExtension.UploadFile(PicturePath, "wwwroot/static/uploads/categories").Replace(@"\", "/");
            context.Categories.Add(category);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Esram.Davetiye.Web.App/Areas/ritapanel/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Esram.Davetiye.Web.App.Areas.ritapanel.Models.ViewModels;
using Esram.Davetiye.Web.App.Manage.Filters;
using Esram.Davetiye.Web.App.Models.Context;
using Esram.Davetiye.Web.App.Models.Entities;
using Esram.Davetiye.Web.App.Models.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Esram.Davetiye.Web.App.Areas.ritapanel.Controllers
{
    [Authentication]
    [Area("ritapanel")]
    public class ProductController : Controller
    {
        [Route("ritapanel/davetiyeler")]
        public async Task<IActionResult> Index()
        {
            using var context = new EsramDbContext();
            var mcs = await context.MasterCategories.Include(m => m.Categories).ToListAsync();
            return View(mcs);
        }

        [HttpPost]
        [Route("getcatbymaster")]
        public async Task<IActionResult> GetCategoriesByMaster(int mcid)
        {
            using var context = new EsramDbContext();
            var cats = await context.Categories.Where(x => x.MasterCategoryId == mcid).OrderByDescending(x => x.Id).ToListAsync();
            return Json(cats);
        }

        [HttpPost]
        [Route("changeproductlist")]
        public IActionResult ChangeProductList(int mcid, int cid)
        {
            return ViewComponent("ProductTable", new { mcid = mcid, cid = cid });
        }

        [Route("ritapanel/urun-guncelle/{id}")]
        public async Task<IActionResult> EditProduct(int id)
        {
            using var context = new EsramDbContext();
            var product = await context.Products.Include(x => x.Pictures).FirstOrDefaultAsync(x => x.Id == id);
            return View(product);
        }

        [HttpPost]
        [Route("ritapanel/urun-guncelle/{id}")]
        public async Task<IActionResult> EditProduct(Product product)
        {
            using var context = new EsramDbContext();
            var current = await context.Products.Include(x => x.Pictures).FirstOrDefaultAsync(x => x.Id == product.Id);
            if (ModelState.IsValid)
            {
                current.Name = product.Name;
                current.IsBest = product.IsBest;
                current.MainPicture = product.MainPicture;
                current.Code = product.Code;
                current.Price = product.Price;
                current.Description = product.Description;
                context.Products.Update(current);
                int result = await context.SaveChangesAsync();

                if (result > 0)
                {
                    ViewBag.Success = "Ürün başarıyla güncellendi";
                }
                else
                {
                    ViewBag.Error = "Ürün güncellenirken bir hata oluştu";
                }
            }
            return View(current);
        }

        [HttpPost]
        [Route("delete-gallery")]
        public async Task<IActionResult> DeleteGallery(int gid)
        {
            using var context = new EsramDbContext();
            ProductPicture pic = await context.ProductPictures.FindAsync(gid);
            context.ProductPictures.Remove(pic);
            FileExtension.RemoveFile(pic.Path);
            int result = await context.SaveChangesAsync();
            return Json(result > 0);
        }

        [HttpPost]
        [Route("edit-pictures")]
        public async Task<IActionResult> EditPictures(IFormFile MainPicture, List<IFormFile> Pictures, int productId)
        {
            using var context = new EsramDbContext();
            Product prod = await context.Products.FindAsync(productId);
            if (MainPicture != null)
            {
                if (prod.MainPicture != null)
                    FileExtension.RemoveFile(prod.MainPicture);
                prod.MainPicture = FileExtension.UploadFile(MainPicture, "wwwroot/static/uploads/products").Replace(@"\", "/");
                context.Products.Update(prod);
            }
            if (Pictures.Count > 0)
            {
                List<ProductPicture> pList = new List<ProductPicture>();
                foreach (var pic in Pictures)
                {
                    pList.Add(new ProductPicture
                    {
                        Path = FileExtension.UploadFile(pic, "wwwroot/static/uploads/products").Replace(@"\", "/"),
                        ProductId = productId
                    });
                }
                await context.ProductPictures.AddRangeAsync(pList);
            }
            await context.SaveChangesAsync();
            return RedirectToAction("EditProduct", prod);
        }

        [HttpPost]
        [Route("delete-product")]
        public async Task<IActionResult> DeleteProduct(int pid)
        {
            using var context = new EsramDbContext();
            var prod = await context.Products.FindAsync(pid);
            context.Products.Remove(prod);
            int result = await context.SaveChangesAsync();
            return Json(result > 0);
        }

        [Route("ritapanel/urun-ekle")]
        public IActionResult CreateProduct()
        {
            using var context = new EsramDbContext();
            CreateProductViewModel vm = new CreateProductViewModel();
            vm.Product = new Product();
            vm.MasterCategories = context.MasterCategories.Include(x => x.Categories).ToList();
            return View(vm);
        }
        [HttpPost]
        [Route("ritapanel/urun-ekle")]
        public async Task<IActionResult> CreateProduct(Product product, IFormFile MainPicture, List<IFormFile> Pictures)
        {
            CreateProductViewModel vm = new CreateProductViewModel();
            using var context = new EsramDbContext();
            vm.MasterCategories = context.MasterCategories.Include(x => x.Categories).ToList();
            vm.Product = new Product();
            if (ModelState.IsValid)
            {
                product.MainPicture = FileExtension.UploadFile(MainPicture, "wwwroot/static/uploads/products").Replace(@"\", "/");

                if (Pictures.Count > 0)
                {
                    product.Pictures = new List<ProductPicture>();
                    foreach (var item in Pictures)
                    {
                        product.Pictures.Add(new ProductPicture
                        {
                            Path = FileExtension.UploadFile(item, "wwwroot/static/uploads/products").Replace(@"\", "/")
                        });
                    }
                }

                await context.Products.AddAsync(product);
                int result = await context.SaveChangesAsync();
                ViewBag.Success = "Ürün başarıyla eklendi";
                return View(vm);
            }
            return View(vm);
        }
    }
}

Esram.Davetiye.Web.App/Areas/ritapanel/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Esram.Davetiye.Web.App.Manage.Filters;
using Esram.Davetiye.Web.App.Models.Context;
using Esram.Davetiye.Web.App.Models.Entities;
using Esram.Davetiye.Web.App.Models.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Esram.Davetiye.Web.App.Areas.ritapanel.Controllers
{
    [Authentication]
    [Area("ritapanel")]
    public class SliderController : Controller
    {
        [Route("ritapanel/slider")]
        public async Task<IActionResult> Index()
        {
            using var context = new EsramDbContext();
            var sliders = await context.Sliders.OrderBy(x => x.Index).ToListAsync();
            return View(sliders);
        }

        [HttpPost]
        [Route("changeslidercard")]
        public IActionResult ChangeSliderCard(int sid)
        {
            return ViewComponent("SliderCard", sid);
        }

        [HttpPost]
        [Route("deleteslider")]
        public async Task<IActionResult> DeleteSlider(int sid)
        {
            using var context = new EsramDbContext();
            var slider = await context.Sliders.FirstOrDefaultAsync(x => x.Id == sid);
            context.Sliders.Remove(slider);
            int result = await context.SaveChangesAsync();
            if (result>0)
            {
                FileExtension.RemoveFile(slider.Path);
                return Json(true);
            }
            return Json(false);
        }

        [HttpPost]
        [Route("editslider")]
        public async Task<IActionResult> EditSlider(int id,int index, IFormFile path,string currentpath)
        {
            using var context = new EsramDbContext();
            var slider = await context.Sliders.FindAsync(id);
            slider.Index = index;
            if (path != null)
                slider.Path = FileExtension.UploadFile(path, "wwwroot/static/uploads/sliders").Replace(@"\", "/");
            context.Sliders.Update(slider);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("newslider")]
        public async Task<IActionResult> NewSlider(int index, IFormFile path)
        {
            using var context = new EsramDbContext();
            var slider = new Slider
            {
                Index = index,
                Path = FileExtension.UploadFile(path, "wwwroot/static/uploads/sliders").Replace(@"\","/")
            };
            context.Sliders.Add(slider);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/addcategorymodal.cshtml
@model Category
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Kategori Düzenle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form asp-action="AddCategory" asp-controller="Category" asp-area="ritapanel" enctype="multipart/form-data" id="frmAddCategory" method="post" class="form p-5">
        <input type="hidden" asp-for="MasterCategoryId"/>
        <div class="form-group">
            <label>Kategori adı :</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <div class="row">
                <div class="col-md-3"><img src="~/@Model.PicturePath" alt="Alternate Text" /></div>
                <div class="col-md-9">
                    <label>Görsel :</label>
                    <input type="file" name="PicturePath" asp-for="PicturePath" class="form-control" />
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
    <button type="button" id="btnAdd" class="btn btn-primary">Kaydet</button>
</div>

<script>
    $('#btnAdd').click(function (e) {
        e.preventDefault();
        if (confirm("Kaydetmek istediğinize emin misiniz?")) {
            $('#frmAddCategory').submit();
        }
    })
</script>

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/editcategorymodal.cshtml
@model Category
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Alt kategori Düzenle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form asp-action="EditCategory" asp-controller="Category" asp-area="ritapanel" enctype="multipart/form-data" id="frmEdit" method="post" class="form p-5">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="PicturePath" />
        <input type="hidden" asp-for="MasterCategoryId" />
        <div class="form-group">
            <label>Kategori adı :</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <div class="row">
                <div class="col-md-3"><img src="~/@Model.PicturePath" alt="Alternate Text" /></div>
                <div class="col-md-9">
                    <label>Görsel :</label>
                    <input type="file" name="PicturePath" asp-for="PicturePath" class="form-control" />
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
    <button type="button" id="btnEdit" class="btn btn-primary">Kaydet</button>
</div>

<script>
    $('#btnEdit').click(function (e) {
        e.preventDefault();
        if (confirm("Değişiklikleri kaydetmek istediğinize emin misiniz?")) {
            $('#frmEdit').submit();
        }
    })
</script>

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/editmodal.cshtml
@model MasterCategory
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Kategori Düzenle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form asp-action="EditMasterCategory" asp-controller="Category" asp-area="ritapanel" enctype="multipart/form-data" id="frmEdit" method="post" class="form p-5">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="PicturePath" />
        <div class="form-group">
            <label>Kategori adı :</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Sıralama :</label>
            <input type="text" asp-for="Index" class="form-control" />
            <span asp-validation-for="Index" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <div class="row">
                <div class="col-md-3"><img src="~/@Model.PicturePath" alt="Alternate Text" /></div>
                <div class="col-md-9">
                    <label>Görsel :</label>
                    <input type="file" name="PicturePath" asp-for="PicturePath" class="form-control" />
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
    <button type="button" id="btnEdit" class="btn btn-primary">Kaydet</button>
</div>

<script>
    $('#btnEdit').click(function (e) {
        e.preventDefault();
        if (confirm("Değişiklikleri kaydetmek istediğinize emin misiniz?")) {
            $('#frmEdit').submit();
        }
    })
</script>

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/navbar.cshtml
@model ChangePasswordViewModel
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="/ritapanel"><img height="100" src="~/@Esram.Davetiye.Web.App.Manage.Sessions.CorporateSession.Corporate.LogoPath" alt="Alternate Text" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link mr-md-5 ml-md-5" href="/"><i class="fa fa-home text-info"></i> Siteye Git</a>
            <a class="nav-item nav-link d-none d-sm-block" href="/ritapanel"><i class="fa fa-info text-info"></i> Kurumsal</a>
            <a class="nav-item nav-link" href="/ritapanel/kategoriler"><i class="fa fa-list text-info"></i> Kategoriler</a>
            <a class="nav-item nav-link" href="/ritapanel/davetiyeler"><i class="fa fa-book text-info"></i> Davetiyeler</a>
            <a class="nav-item nav-link" href="/ritapanel/slider"><i class="fa fa-image text-info"></i> Slider Yönetimi</a>
            <a class="nav-item nav-link" href="javascript:void(0)" data-toggle="modal" data-target="#changePasswordModal"><i class="fa fa-user text-info"></i> Şifre Değiştir</a>
            <a class="nav-item nav-link text-danger d-none d-sm-block" href="/cikis"><i class="fa fa-sign-out"></i> Çıkış</a>
        </div>
    </div>
</nav>

<div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id="ModalContent" class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Şifre değiştir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @*<form class="p-4" asp-area="ritapanel" asp-controller="Account" asp-action="ChangePassword" enctype="multipart/form-data" method="post">*@
            <div class="p-3">
                <div class="form-group">
                    <label>Mevcut şifre :</label>
                    <input class="form-control" type="password" id="currentPassword" required />
                </div>
                <div class="form-group">
                    <label>Yeni şifre :</label>
                    <input class="form-control" type="password" id="password" required />
                </div>
                <div class="form-group">
                    <label>Yeni şifre tekrar :</label>
                    <input class="form-control" type="password" id="confirmPassword" required />
                </div>
                <div class="form-group">
                    <span class="text-danger" id="errorMessage"></span>
                    <span class="text-success" id="successMessage"></span>
                </div>
                <div class="form-group">
                    <button class="btn btn-outline-info btn-block" id="btnChangePassword">Güncelle</button>
                </div>
            </div>
            @*</form>*@
        </div>
    </div>
</div>

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/producttable.cshtml
@model List<Product>

<table class="w-100 table-hover table">
    <thead>
        <tr>
            <th>Resim</th>
            <th>Kategori</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Fiyat</th>
            <th>Seçenekler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
            <tr id="product-@p.Id">
                <td><img src="~/@p.MainPicture" width="50" alt="Alternate Text" /></td>
                <td>@p.Category.Name</td>
                <td>@p.Name</td>
                <td>@p.Code</td>
                <td>@p.Price</td>
                <td>
                    <a class="" href="/ritapanel/urun-guncelle/@p.Id" style="font-size:20px;"><i class="fa fa-edit text-warning"></i></a>
                    <a class="ml-3" href="javascript:void(0)" onclick="DeleteProduct(@p.Id)" style="font-size:20px;"><i class="fa fa-trash text-danger"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    
</script>

Esram.Davetiye.Web.App/Areas/ritapanel/Views/ViewComponents/slidercard.cshtml
@model Slider
@if (Model != null)
{
    <div class="row pr-md-2">
        <div class="col-md-10">
            <form id="frmEdit" asp-area="ritapanel" asp-controller="Slider" asp-action="EditSlider" enctype="multipart/form-data" method="post">
                <div class="form-row pt-md-2 pl-md-2">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <input type="hidden" name="currentpath" value="@Model.Path" />
                    <div class="form-group col-md-1">
                        <input class="form-control" type="number" name="index" value="@Model.Index" />
                    </div>
                    <div class="form-group col-md-2 pt-md-1">
                        <input class="form-control-file" type="file" name="path" />
                    </div>
                    <div class="form-group col-md-2">
                        <input class="form-control btn btn-outline-info" id="btnEdit" type="submit" value="Güncelle" />
                    </div>

                </div>
            </form>
        </div>
        <div class="col-md-1 offset-md-1 text-right pt-md-2">
            <button onclick="DeleteSlider(@Model.Id)" class="btn btn-danger text-white"><i class="fa fa-trash"></i></button>
        </div>
    </div>
    @*<div class="card-body p-0 text-center">
            <h5 class="card-title badge-light p-1">

                <button class="btn btn-warning btn-sm text-white"><i class="fa fa-edit"></i></button>

            </h5>
        </div>*@
    <img src="~/@Model.Path" class="card-img-bottom" alt="...">
}